# Multi-cycle recurrent-selection simulation for evaluating a desired-gain
# vector.
#
# The purpose of this simulation is narrow and should stay narrow: it exists to
# compare desired-gain directions over several cycles, not to design a crossing
# plan. Parent, cross and mating decisions belong to a dedicated mating-design
# tool. Consequently the selection rule here is deliberately simple.

#' Mean pairwise genomic relationship among a population
#'
#' @param pop An AlphaSimR population.
#' @param SP AlphaSimR simulation parameters.
#'
#' @return The mean off-diagonal relationship, used as a diversity proxy.
#' @noRd
.dgr_mean_relationship <- function(pop, SP) {
  geno <- AlphaSimR::pullQtlGeno(pop, simParam = SP)
  if (is.null(dim(geno)) || nrow(geno) < 2L) return(NA_real_)
  frequency <- colMeans(geno) / 2
  keep <- frequency > 0 & frequency < 1
  if (!any(keep)) return(NA_real_)
  geno <- geno[, keep, drop = FALSE]
  frequency <- frequency[keep]
  centred <- sweep(geno, 2L, 2 * frequency, "-")
  scaling <- 2 * sum(frequency * (1 - frequency))
  relationship <- tcrossprod(centred) / scaling
  mean(relationship[upper.tri(relationship)])
}

#' Effective population size implied by a change in relationship
#'
#' @param before,after Mean relationship before and after one cycle.
#'
#' @return An approximate effective population size, or `NA_real_`.
#' @noRd
.dgr_effective_size <- function(before, after) {
  if (!is.finite(before) || !is.finite(after)) return(NA_real_)
  delta <- (after - before) / (2 * (1 - before))
  if (!is.finite(delta) || delta <= 0) return(NA_real_)
  1 / (2 * delta)
}

#' Index coefficients for a desired-gain direction
#'
#' Uses the Yamada formulation, which is the one [run_dgsi()] implements.
#'
#' @param d Desired-gain direction.
#' @param G,P Covariance matrices in the analysis space.
#' @param ridge Small ridge added to both solves.
#'
#' @return Named index coefficients.
#' @noRd
.dgr_yamada_coefficients <- function(d, G, P, ridge = 1e-8) {
  p <- length(d)
  P_ridged <- P + diag(ridge, p)
  Xpg <- solve(P_ridged, G)
  middle <- crossprod(G, Xpg)
  middle <- (middle + t(middle)) / 2 + diag(ridge, p)
  coefficients <- as.numeric(Xpg %*% solve(middle, d))
  names(coefficients) <- names(d)
  coefficients
}

#' Simulate recurrent selection under a fixed desired-gain direction
#'
#' Runs a recurrent-selection programme forward for a stated number of cycles,
#' selecting each cycle on a desired-gain index built from the supplied
#' direction, and records the cumulative genetic gain and the loss of genetic
#' variation. The purpose is to compare desired-gain directions, because a
#' direction that maximises response in the first cycle may exhaust the
#' variance that response depends on within a few more.
#'
#' @details
#' # What the simulation adds beyond the single-cycle formula
#'
#' A single-cycle response prediction cannot distinguish desired-gain
#' directions beyond what the achievable-response ellipsoid already states, and
#' [gain_feasibility()] gives that answer exactly and without simulation.
#' Simulation is informative only because it represents the processes that make
#' cycle five differ from cycle one: (i) the reduction and reshaping of genetic
#' variance caused by truncation selection, (ii) drift and the accumulation of
#' relatedness in a finite population, (iii) the point at which an antagonistic
#' correlation drives a secondary trait past an unacceptable level, and (iv)
#' the compounding of estimation error when the index is rebuilt each cycle.
#'
#' # Mating systems
#'
#' \describe{
#'   \item{`"self"`}{Self-pollinated line development. Selected parents are
#'     intercrossed, and the resulting families are advanced by selfing or
#'     doubled haploidy before evaluation. Recombination therefore releases
#'     variation slowly.}
#'   \item{`"outcross"`}{Recurrent selection in a random-mating population.
#'     Selected parents are intercrossed each cycle, so half the disequilibrium
#'     generated by selection decays per generation.}
#'   \item{`"clonal"`}{Clonally propagated crops. Selection acts on total
#'     genetic value rather than breeding value, because the clone inherits
#'     dominance intact. This mating system therefore requires a setup built
#'     with `dominance_degree`, and `G` should be the genotypic covariance.}
#' }
#'
#' # Index re-estimation
#'
#' With `reestimate_index = TRUE`, the covariance matrices are re-estimated
#' from each cycle's own simulated data, which is what a breeding programme
#' actually does and which propagates estimation error across cycles. With
#' `FALSE`, the coefficients from cycle one are reused, which isolates the
#' effect of the desired-gain direction itself. A large divergence between the
#' two settings means the recommendation is sensitive to estimation error, and
#' the breeder should be told so.
#'
#' @param setup An object from [founder_population()].
#' @param desired_gains Named desired-gain direction. Only the direction
#'   matters, because the attainable magnitude is fixed by selection intensity.
#' @param n_cycles Number of selection cycles.
#' @param mating_system One of `"self"`, `"outcross"`, or `"clonal"`.
#' @param n_parents Number of parents recycled each cycle. Fewer parents
#'   increase short-term gain and reduce long-term potential.
#' @param n_crosses Number of crosses made each cycle.
#' @param n_progeny_per_cross Progeny evaluated per cross.
#' @param n_selfing_generations Selfing generations before evaluation, used by
#'   `"self"` when `use_doubled_haploids` is `FALSE`.
#' @param use_doubled_haploids Whether `"self"` produces doubled haploids
#'   instead of advancing by selfing.
#' @param lower_is_better Traits for which smaller values are favourable.
#' @param reestimate_index Whether to rebuild the index from each cycle's own
#'   simulated data. See Details.
#' @param seed Random seed. The caller's random number generator state is
#'   restored on exit.
#'
#' @return An object of class `desiredgainr_simulation` containing a per-cycle
#'   table of genetic means, genetic variances, mean relationship and effective
#'   population size, together with the cumulative gain per trait.
#'
#' @seealso [founder_population()], [gain_feasibility()]
#' @export
simulate_selection_cycles <- function(
    setup,
    desired_gains,
    n_cycles = 5L,
    mating_system = c("self", "outcross", "clonal"),
    n_parents = 20L,
    n_crosses = 50L,
    n_progeny_per_cross = 10L,
    n_selfing_generations = 3L,
    use_doubled_haploids = FALSE,
    lower_is_better = NULL,
    reestimate_index = TRUE,
    seed = 42L
) {
  .dgr_require_alphasimr("simulate_selection_cycles()")
  mating_system <- match.arg(mating_system)
  if (!inherits(setup, "desiredgainr_sim_setup")) {
    stop("setup must be created by founder_population().", call. = FALSE)
  }
  if (mating_system == "clonal" && !isTRUE(setup$dominance)) {
    stop(
      "mating_system = 'clonal' requires a setup built with ",
      "dominance_degree, because selection acts on total genetic value.",
      call. = FALSE
    )
  }
  trait_cols <- setup$trait_cols
  d <- .dgr_named_vector(desired_gains, trait_cols, "desired_gains")
  if (all(d == 0)) {
    stop("desired_gains must contain at least one non-zero element.",
         call. = FALSE)
  }
  n_cycles <- .dgr_positive_integer(n_cycles, "n_cycles")
  n_parents <- .dgr_positive_integer(n_parents, "n_parents")
  n_crosses <- .dgr_positive_integer(n_crosses, "n_crosses")
  n_progeny_per_cross <- .dgr_positive_integer(
    n_progeny_per_cross, "n_progeny_per_cross"
  )

  direction <- rep(1, length(trait_cols))
  names(direction) <- trait_cols
  if (length(lower_is_better)) {
    unknown <- setdiff(lower_is_better, trait_cols)
    if (length(unknown)) {
      stop("Unknown lower_is_better traits: ",
           paste(unknown, collapse = ", "), call. = FALSE)
    }
    direction[lower_is_better] <- -1
  }

  if (!exists(".Random.seed", envir = globalenv(), inherits = FALSE)) {
    stats::runif(1L)
  }
  entry_seed <- get(".Random.seed", envir = globalenv(), inherits = FALSE)
  on.exit(assign(".Random.seed", entry_seed, envir = globalenv()), add = TRUE)
  set.seed(as.integer(seed))

  SP <- setup$SP

  # Genetic gain must be tracked on an absolute scale. AlphaSimR's bv() returns
  # breeding values expressed relative to the supplied population, so its
  # column means are zero for every population and a difference between cycles
  # would always be zero. gv() is anchored by the trait mean fixed when the
  # trait was added, and is therefore the quantity whose change across cycles
  # is genetic gain.
  merit_of <- function(pop) {
    values <- AlphaSimR::gv(pop)
    colnames(values) <- trait_cols
    values
  }

  # Estimating the covariance used to rebuild the index is a separate question.
  # For an additive programme the index should be built on additive covariance,
  # and centring does not affect a covariance, so bv() is appropriate there.
  # For a clonal programme the clone inherits dominance intact, so the
  # genotypic covariance is the relevant one.
  genetic_for_covariance <- function(pop) {
    values <- if (mating_system == "clonal") {
      AlphaSimR::gv(pop)
    } else {
      AlphaSimR::bv(pop, simParam = SP)
    }
    colnames(values) <- trait_cols
    values
  }

  current <- setup$founder_pop
  baseline_merit <- colMeans(merit_of(current))
  names(baseline_merit) <- trait_cols
  previous_relationship <- .dgr_mean_relationship(current, SP)

  fixed_coefficients <- NULL
  records <- vector("list", n_cycles)

  for (cycle in seq_len(n_cycles)) {
    # Develop the evaluation population for this cycle.
    if (mating_system == "self") {
      progeny <- AlphaSimR::randCross(
        current, nCrosses = n_crosses, nProgeny = n_progeny_per_cross,
        simParam = SP
      )
      evaluation <- if (isTRUE(use_doubled_haploids)) {
        AlphaSimR::makeDH(progeny, nDH = 1L, simParam = SP)
      } else {
        advanced <- progeny
        for (generation in seq_len(n_selfing_generations)) {
          advanced <- AlphaSimR::self(advanced, nProgeny = 1L, simParam = SP)
        }
        advanced
      }
    } else {
      # Both the outcrossing and clonal systems evaluate the F1 generation;
      # they differ in whether dominance is transmitted to the next cycle,
      # which is handled by merit_of() rather than by the crossing step.
      evaluation <- AlphaSimR::randCross(
        current, nCrosses = n_crosses, nProgeny = n_progeny_per_cross,
        simParam = SP
      )
    }
    evaluation <- AlphaSimR::setPheno(evaluation, simParam = SP)

    phenotypes <- AlphaSimR::pheno(evaluation)
    colnames(phenotypes) <- trait_cols

    oriented_pheno <- sweep(phenotypes, 2L, direction, "*")
    oriented_genetic <- sweep(
      genetic_for_covariance(evaluation), 2L, direction, "*"
    )

    coefficients <- if (!is.null(fixed_coefficients) &&
                        !isTRUE(reestimate_index)) {
      fixed_coefficients
    } else {
      P_hat <- stats::cov(oriented_pheno)
      G_hat <- stats::cov(oriented_genetic)
      dimnames(P_hat) <- dimnames(G_hat) <- list(trait_cols, trait_cols)
      .dgr_yamada_coefficients(d, G_hat, P_hat)
    }
    if (is.null(fixed_coefficients)) fixed_coefficients <- coefficients

    score <- as.numeric(oriented_pheno %*% coefficients)
    keep <- order(-score)[seq_len(min(n_parents, length(score)))]
    selected <- evaluation[keep]

    relationship <- .dgr_mean_relationship(selected, SP)
    cycle_merit <- colMeans(merit_of(evaluation))
    names(cycle_merit) <- trait_cols
    cycle_variance <- apply(merit_of(evaluation), 2L, stats::var)

    records[[cycle]] <- data.table::data.table(
      cycle = cycle,
      trait = trait_cols,
      genetic_mean = as.numeric(cycle_merit),
      cumulative_gain = as.numeric(cycle_merit - baseline_merit),
      genetic_variance = as.numeric(cycle_variance),
      mean_relationship = relationship,
      effective_size = .dgr_effective_size(previous_relationship, relationship),
      selection_intensity = .dgr_intensity(n_parents / AlphaSimR::nInd(evaluation)),
      n_evaluated = AlphaSimR::nInd(evaluation)
    )
    previous_relationship <- relationship
    current <- selected
  }

  cycle_table <- data.table::rbindlist(records)
  final <- cycle_table[cycle == max(cycle)]
  cumulative <- stats::setNames(final$cumulative_gain, final$trait)

  result <- list(
    desired_gains = d,
    direction = direction,
    mating_system = mating_system,
    n_cycles = n_cycles,
    n_parents = n_parents,
    reestimate_index = reestimate_index,
    cycle_table = cycle_table,
    cumulative_gain = cumulative,
    final_variance = stats::setNames(final$genetic_variance, final$trait),
    final_relationship = final$mean_relationship[1L],
    coefficients_cycle_one = fixed_coefficients,
    seed = as.integer(seed),
    scope = paste(
      "This simulation compares desired-gain directions. It is not a crossing",
      "plan, and its selection rule is deliberately simple truncation on the",
      "index. Parent, cross and mating allocation require a dedicated",
      "mating-design tool."
    )
  )
  class(result) <- c("desiredgainr_simulation", "list")
  result
}

#' @export
print.desiredgainr_simulation <- function(x, ...) {
  cat("<desiredgainr_simulation>\n")
  cat(sprintf(
    "  %s system, %d cycles, %d parents recycled\n",
    x$mating_system, x$n_cycles, x$n_parents
  ))
  cat("  Index re-estimated each cycle:",
      if (isTRUE(x$reestimate_index)) "yes" else "no", "\n")
  cat("  Cumulative genetic gain:\n")
  print(round(x$cumulative_gain, 4L))
  cat(sprintf(
    "  Final mean relationship among parents: %.4f\n",
    x$final_relationship
  ))
  invisible(x)
}
